
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := mxc_ipudev_test
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES :=  bin/mxc_ipudev_test
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mxc_vpu_test
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES :=  bin/mxc_vpu_test
include $(BUILD_PREBUILT)
