#
# SoC-specific compile-time definitions.
#

BOARD_SOC_TYPE := IMX6DQ
BOARD_HAVE_VPU := true
HAVE_FSL_IMX_GPU2D := true
HAVE_FSL_IMX_GPU3D := true
HAVE_FSL_IMX_IPU := true
BOARD_KERNEL_BASE := 0x10800000
TARGET_KERNEL_DEFCONF := imx6_android_defconfig
HAVE_FSL_IMX_CODEC := true
TARGET_HAVE_IMX_GRALLOC := true
TARGET_HAVE_IMX_HWCOMPOSER = true
USE_OPENGL_RENDERER := true
TARGET_CPU_SMP := true

