
add_lunch_combo arm2_6dq-eng
add_lunch_combo arm2_6dq-user
add_lunch_combo sabresd_6dq-eng
add_lunch_combo sabresd_6dq-user
add_lunch_combo sabreauto_6q-eng
add_lunch_combo sabreauto_6q-user
add_lunch_combo arm2_6sl-eng
add_lunch_combo arm2_6sl-user
add_lunch_combo arm2_6sl_eink-eng
add_lunch_combo arm2_6sl_eink-user
add_lunch_combo evk_6sl-eng
add_lunch_combo evk_6sl-user
add_lunch_combo evk_6sl_eink-eng
add_lunch_combo evk_6sl_eink-user
