
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libIpuRender.so
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := lib/libIpuRender.so
LOCAL_MODULE_TAGS := eng
include $(BUILD_PREBUILT)

